/* eslint-disable react/no-unescaped-entities */
import React from "react";
import AboutSections from "@/components/AboutSections";
import PrivacyPolicyAnimation from "@/assets/lottiefiles/privacy-policy.json";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy",
};

const PrivacyPolicy = () => {
  return (
    <div className="w-full pt-28 pb-0 sm:pb-0">
      <header className="homeLayout mb-10">
        <h1 className="p-5 text-3xl font-extrabold rowdies text-gray-800 text-center sm:text-5xl">
          Privacy Policy
        </h1>
      </header>
      <div className="w-full min-h-screen max-h-full">
        <AboutSections
          title1="MSBTEQuizPro"
          title2=""
          content1="This Privacy Policy describes our policies and procedures on the collection, use, and disclosure of your information when you use the MSBTE Quiz Pro service and tells you about your privacy rights and how the law protects you.
We use your personal data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator."
          content2=""
          settings={{
            flex: "flex-row",
            animation: PrivacyPolicyAnimation,
            bgColor: "bg-gray-100",
          }}
        />
        <div className="w-full px-5 sm:homeLayout flex flex-wrap flex-col text-gray-800 sm:justify-between py-16 sm:py-20 sm:pb-32 xl:py-10 ">
          <h2 className="text-2xl font-semibold mt-8 mb-4">
            Interpretation and Definitions
          </h2>

          <h3 className="text-xl font-semibold mb-2">Interpretation</h3>
          <p className="mb-4">
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in
            singular or in plural.
          </p>

          <h3 className="text-xl font-semibold mb-2">Definitions</h3>
          <ul className="list-disc pl-6 mb-4">
            <li>
              <strong>Account:</strong> means a unique account created for you
              to access our Service or parts of our Service.
            </li>
            <li>
              <strong>Affiliate:</strong> means an entity that controls, is
              controlled by, or is under common control with a party, where
              "control" means ownership of 50% or more of the shares, equity
              interest, or other securities entitled to vote for the election of
              directors or other managing authority.
            </li>
            <li>
              <strong>Company:</strong> (referred to as either the Company
              ,"We", "Us", or "Our" in this Agreement) refers to MSBTE Quiz
              Pro.
            </li>
            <li>
              <strong>Cookies:</strong> are small files that are placed on your
              computer, mobile device, or any other device by a website,
              containing the details of your browsing history on that website
              among its many uses.
            </li>
            <li>
              <strong>Country:</strong> refers to Maharashtra, India.
            </li>
            <li>
              <strong>Device:</strong> means any device that can access the
              Service such as a computer, a cellphone, or a digital tablet.
            </li>
            <li>
              <strong>Personal Data:</strong> is any information that relates to
              an identified or identifiable individual.
            </li>
            <li>
              <strong>Service:</strong> refers to the Website.
            </li>
            <li>
              <strong>Service Provider:</strong> means any natural or legal
              person who processes the data on behalf of the Company. It refers
              to third-party companies or individuals employed by the Company to
              facilitate the Service, provide the Service on behalf of the
              Company, perform services related to the Service, or assist the
              Company in analyzing how the Service is used.
            </li>
            <li>
              <strong>Third-Party Social Media Service:</strong> refers to any
              website or social network website through which a user can log in
              or create an account to use the Service.
            </li>
            <li>
              <strong>Usage Data:</strong> refers to data collected
              automatically, either generated by the use of the Service or from
              the Service infrastructure itself (for example, the duration of a
              page visit).
            </li>
            <li>
              <strong>Website:</strong> refers to MSBTE Quiz Pro, accessible
              from{" "}
              <a
                href={`${process.env.BASE_URL}`}
                className="text-blue-500 underline"
              >
                {`${process.env.BASE_URL}`}
              </a>
              .
            </li>
            <li>
              <strong>You:</strong> means the individual accessing or using the
              Service, or the company, or other legal entity on behalf of which
              such individual is accessing or using the Service, as applicable.
            </li>
          </ul>


          <h2 className="text-2xl font-semibold mt-8 mb-4">
            Collecting and Using Your Personal Data
          </h2>

          <h3 className="text-xl font-semibold mb-2">
            Types of Data Collected
          </h3>

          <h4 className="text-lg font-semibold mb-2">Personal Data</h4>
          <p className="mb-4">
            While using our Service, we may ask you to provide us with certain
            personally identifiable information that can be used to contact or
            identify you. Personally identifiable information may include, but
            is not limited to:
          </p>
          <ul className="list-disc pl-6 mb-4">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
          </ul>

          <h2 className="text-2xl font-semibold mb-4">Usage Data</h2>
          <p className="mb-4">
            Usage Data is collected automatically when using the Service. Usage
            Data may include information such as your Device's Internet Protocol
            address (e.g., IP address), browser type, browser version, the pages
            of our Service that you visit, the time and date of your visit, the
            time spent on those pages, unique device identifiers, and other
            diagnostic data.
          </p>
          <p className="mb-4">
            When you access the Service by or through a mobile device, we may
            collect certain information automatically, including, but not
            limited to, the type of mobile device you use, your mobile device
            unique ID, the IP address of your mobile device, your mobile
            operating system, the type of mobile Internet browser you use,
            unique device identifiers, and other diagnostic data.
          </p>
          <p className="mb-4">
            We may also collect information that your browser sends whenever you
            visit our Service or when you access the Service by or through a
            mobile device.
          </p>

          <h2 className="text-2xl font-semibold mb-4">
            Information from Third-Party Social Media Services
          </h2>
          <p className="mb-4">
            The Company allows you to create an account and log in to use the
            Service through the following Third-Party Social Media Services:
          </p>
          <ul className="list-disc pl-5 mb-4">
            <li>Google</li>
          </ul>
          <p className="mb-4">
            If you decide to register through or otherwise grant us access to a
            Third-Party Social Media Service, we may collect Personal Data that
            is already associated with your Third-Party Social Media Service's
            account, such as your name, email address, activities, or your
            contact list associated with that account.
          </p>
          <p className="mb-4">
            You may also have the option of sharing additional information with
            the Company through your Third-Party Social Media Service's account.
            If you choose to provide such information and Personal Data, during
            registration or otherwise, you are giving the Company permission to
            use, share, and store it in a manner consistent with this Privacy
            Policy.
          </p>

          <h2 className="text-2xl font-semibold mb-4">
            Tracking Technologies and Cookies
          </h2>
          <p className="mb-4">
            We use Cookies and similar tracking technologies to track the
            activity on our Service and store certain information. Tracking
            technologies used are beacons, tags, and scripts to collect and
            track information and to improve and analyze our Service. The
            technologies we use may include:
          </p>

          <h3 className="text-xl font-semibold mb-2">
            Cookies or Browser Cookies
          </h3>
          <p className="mb-4">
            A cookie is a small file placed on your Device. You can instruct
            your browser to refuse all Cookies or to indicate when a Cookie is
            being sent. However, if you do not accept Cookies, you may not be
            able to use some parts of our Service. Unless you have adjusted your
            browser setting so that it will refuse Cookies, our Service may use
            Cookies.
          </p>

          <h3 className="text-xl font-semibold mb-2">Web Beacons</h3>
          <p className="mb-4">
            Certain sections of our Service and our emails may contain small
            electronic files known as web beacons (also referred to as clear
            gifs, pixel tags, and single-pixel gifs) that permit the Company,
            for example, to count users who have visited those pages or opened
            an email and for other related website statistics (for example,
            recording the popularity of a certain section and verifying system
            and server integrity).
          </p>

          <p className="mb-4">
            Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies
            remain on your personal computer or mobile device when you go
            offline, while Session Cookies are deleted as soon as you close your
            web browser.
          </p>

          <h3 className="text-xl font-semibold mb-2">
            Types of Cookies We Use
          </h3>

          <div className="mb-4">
            <h4 className="text-lg font-semibold mb-2">
              Necessary / Essential Cookies
            </h4>
            <p className="mb-2">
              <span className="font-semibold">Type:</span> Session Cookies
            </p>
            <p className="mb-2">
              <span className="font-semibold">Administered by:</span> Us
            </p>
            <p className="mb-4">
              <span className="font-semibold">Purpose:</span> These Cookies are
              essential to provide you with services available through the
              Website and to enable you to use some of its features. They help
              to authenticate users and prevent fraudulent use of user accounts.
              Without these Cookies, the services that you have asked for cannot
              be provided, and we only use these Cookies to provide you with
              those services.
            </p>
          </div>

          <div className="mb-4">
            <h4 className="text-lg font-semibold mb-2">
              Cookies Policy / Notice Acceptance Cookies
            </h4>
            <p className="mb-2">
              <span className="font-semibold">Type:</span> Persistent Cookies
            </p>
            <p className="mb-2">
              <span className="font-semibold">Administered by:</span> Us
            </p>
            <p className="mb-4">
              <span className="font-semibold">Purpose:</span> These Cookies
              identify if users have accepted the use of cookies on the Website.
            </p>
          </div>

          <div className="mb-4">
            <h4 className="text-lg font-semibold mb-2">
              Functionality Cookies
            </h4>
            <p className="mb-2">
              <span className="font-semibold">Type:</span> Persistent Cookies
            </p>
            <p className="mb-2">
              <span className="font-semibold">Administered by:</span> Us
            </p>
            <p className="mb-4">
              <span className="font-semibold">Purpose:</span> These Cookies
              allow us to remember choices you make when you use the Website,
              such as remembering your login details or language preference. The
              purpose of these Cookies is to provide you with a more personal
              experience and to avoid you having to re-enter your preferences
              every time you use the Website.
            </p>
          </div>

          <p className="mb-4">
            For more information about the cookies we use and your choices
            regarding cookies, please visit our Cookies Policy or the Cookies
            section of our Privacy Policy.
          </p>

          <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>

          <section className="mb-6">
            <h2 className="text-2xl font-semibold mb-2">
              Use of Your Personal Data
            </h2>
            <p className="mb-4">
              The Company may use Personal Data for the following purposes:
            </p>
            <ul className="list-disc list-inside mb-4">
              <li className="mb-2">
                <strong>To provide and maintain our Service:</strong> including
                to monitor the usage of our Service.
              </li>
              <li className="mb-2">
                <strong>To manage your Account:</strong> to manage your
                registration as a user of the Service. The Personal Data you
                provide can give you access to different functionalities of the
                Service that are available to you as a registered user.
              </li>
              <li className="mb-2">
                <strong>For the performance of a contract:</strong> the
                development, compliance, and undertaking of the purchase
                contract for the products, items, or services you have purchased
                or of any other contract with us through the Service.
              </li>
              <li className="mb-2">
                <strong>To contact you:</strong> to contact you by email,
                telephone calls, SMS, or other equivalent forms of electronic
                communication, such as a mobile application's push notifications
                regarding updates or informative communications related to the
                functionalities, products, or contracted services, including the
                security updates, when necessary or reasonable for their
                implementation.
              </li>
              <li className="mb-2">
                <strong>
                  To provide you with news, special offers, and general
                  information:
                </strong>{" "}
                about other goods, services, and events which we offer that are
                similar to those that you have already purchased or enquired
                about unless you have opted not to receive such information.
              </li>
              <li className="mb-2">
                <strong>To manage your requests:</strong> to attend and manage
                your requests to us.
              </li>
              <li className="mb-2">
                <strong>For business transfers:</strong> we may use your
                information to evaluate or conduct a merger, divestiture,
                restructuring, reorganization, dissolution, or other sale or
                transfer of some or all of our assets, whether as a going
                concern or as part of bankruptcy, liquidation, or similar
                proceeding, in which Personal Data held by us about our Service
                users is among the assets transferred.
              </li>
              <li className="mb-2">
                <strong>For other purposes:</strong> we may use your information
                for other purposes, such as data analysis, identifying usage
                trends, determining the effectiveness of our promotional
                campaigns, and to evaluate and improve our Service, products,
                services, marketing, and your experience.
              </li>
            </ul>
          </section>

          <section className="mb-6">
            <h2 className="text-2xl font-semibold mb-2">
              We may share your personal information in the following
              situations:
            </h2>
            <ul className="list-disc list-inside mb-4">
              <li className="mb-2">
                <strong>With Service Providers:</strong> we may share your
                personal information with Service Providers to monitor and
                analyze the use of our Service, to contact you.
              </li>
              <li className="mb-2">
                <strong>For business transfers:</strong> we may share or
                transfer your personal information in connection with, or during
                negotiations of, any merger, sale of Company assets, financing,
                or acquisition of all or a portion of our business to another
                company.
              </li>
              <li className="mb-2">
                <strong>With Affiliates:</strong> we may share your information
                with our affiliates, in which case we will require those
                affiliates to honor this Privacy Policy. Affiliates include our
                parent company and any other subsidiaries, joint venture
                partners, or other companies that we control or that are under
                common control with us.
              </li>
              <li className="mb-2">
                <strong>With business partners:</strong> we may share your
                information with our business partners to offer you certain
                products, services, or promotions.
              </li>
              <li className="mb-2">
                <strong>With other users:</strong> when you share personal
                information or otherwise interact in the public areas with other
                users, such information may be viewed by all users and may be
                publicly distributed outside. If you interact with other users
                or register through a Third-Party Social Media Service, your
                contacts on the Third-Party Social Media Service may see your
                name, profile, pictures, and description of your activity.
                Similarly, other users will be able to view descriptions of your
                activity, communicate with you, and view your profile.
              </li>
              <li className="mb-2">
                <strong>With your consent:</strong> we may disclose your
                personal information for any other purpose with your consent.
              </li>
            </ul>
          </section>

          <section className="mb-6">
            <h2 className="text-2xl font-semibold mb-2">
              Retention of Your Personal Data
            </h2>
            <p className="mb-4">
              The Company will retain your Personal Data only for as long as is
              necessary for the purposes set out in this Privacy Policy. We will
              retain and use your Personal Data to the extent necessary to
              comply with our legal obligations (for example, if we are required
              to retain your data to comply with applicable laws), resolve
              disputes, and enforce our legal agreements and policies.
            </p>
            <p className="mb-4">
              The Company will also retain Usage Data for internal analysis
              purposes. Usage Data is generally retained for a shorter period of
              time, except when this data is used to strengthen the security or
              to improve the functionality of our Service, or we are legally
              obligated to retain this data for longer time periods.
            </p>
          </section>

          <section className="mb-6">
            <h2 className="text-2xl font-semibold mb-2">
              Transfer of Your Personal Data
            </h2>
            <p className="mb-4">
              Your information, including Personal Data, is processed at the
              Company's operating offices and in any other places where the
              parties involved in the processing are located. It means that this
              information may be transferred to — and maintained on — computers
              located outside of your state, province, country, or other
              governmental jurisdiction where the data protection laws may
              differ from those from your jurisdiction.
            </p>
            <p className="mb-4">
              Your consent to this Privacy Policy followed by your submission of
              such information represents your agreement to that transfer.
            </p>
            <p className="mb-4">
              The Company will take all steps reasonably necessary to ensure
              that your data is treated securely and in accordance with this
              Privacy Policy and no transfer of your Personal Data will take
              place to an organization or a country unless there are adequate
              controls in place including the security of your data and other
              personal information.
            </p>
          </section>

          <section className="mb-6">
            <h2 className="text-2xl font-semibold mb-2">
              Delete Your Personal Data
            </h2>
            <p className="mb-4">
              You have the right to delete or request that we assist in deleting
              the Personal Data that we have collected about you.
            </p>
            <p className="mb-4">
              Our Service may give you the ability to delete certain information
              about you from within the Service.
            </p>
            <p className="mb-4">
              You may update, amend, or delete your information at any time by
              signing in to your Account, if you have one, and visiting the
              account settings section that allows you to manage your personal
              information. You may also contact us to request access to,
              correct, or delete any personal information that you have provided
              to us.
            </p>
            <p className="mb-4">
              Please note, however, that we may need to retain certain
              information when we have a legal obligation or lawful basis to do
              so.
            </p>
          </section>

          <section className="mb-6">
            <h2 className="text-2xl font-semibold mb-2">
              Disclosure of Your Personal Data
            </h2>
            <ul className="list-disc list-inside mb-4">
              <li className="mb-2">
                <strong>Business Transactions:</strong> If the Company is
                involved in a merger, acquisition, or asset sale, your Personal
                Data may be transferred. We will provide notice before your
                Personal Data is transferred and becomes subject to a different
                Privacy Policy.
              </li>
              <li className="mb-2">
                <strong>Law Enforcement:</strong> Under certain circumstances,
                the Company may be required to disclose your Personal Data if
                required to do so by law or in response to valid requests by
                public authorities (e.g., a court or a government agency).
              </li>
              <li className="mb-2">
                <strong>Other Legal Requirements:</strong> The Company may
                disclose your Personal Data in the good faith belief that such
                action is necessary to:
                <ul className="list-disc list-inside mt-2">
                  <li>Comply with a legal obligation</li>
                  <li>
                    Protect and defend the rights or property of the Company
                  </li>
                  <li>
                    Prevent or investigate possible wrongdoing in connection
                    with the Service
                  </li>
                  <li>
                    Protect the personal safety of users of the Service or the
                    public
                  </li>
                  <li>Protect against legal liability</li>
                </ul>
              </li>
            </ul>
          </section>

          <section className="mb-6">
            <h2 className="text-2xl font-semibold mb-2">
              Security of Your Personal Data
            </h2>
            <p className="mb-4">
              The security of your Personal Data is important to us, but
              remember that no method of transmission over the Internet, or
              method of electronic storage is 100% secure. While we strive to
              use commercially acceptable means to protect your Personal Data,
              we cannot guarantee its absolute security.
            </p>
          </section>


          <div className="mt-3 mb-4">
            <h2 className="text-2xl font-semibold mb-4 text-gray-800">Products/Services</h2>

            <div className="mb-4">
              <h3 className="font-semibold text-gray-700">Products/Services Provided:</h3>
              <p className="text-gray-600 mt-2">
                MSBTE Quiz Pro provides online quizzes designed to help students prepare for MSBTE exams. The quizzes are curated to match the syllabus and are aimed at providing effective practice.
              </p>
            </div>

            <div>
              <h3 className="font-semibold text-gray-700">Service Availability:</h3>
              <p className="text-gray-600 mt-2">
                All services are provided as per availability and may be subject to change based on updates to the MSBTE syllabus or other factors.
              </p>
            </div>
          </div>

          <div className="space-y-4 mt-5 mb-4">
            <h2 className="text-2xl font-semibold text-gray-800">Refunds/Cancellations Policy</h2>
            <div className="space-y-2">
              <h3 className="font-semibold text-gray-700">No Refunds After Purchase:</h3>
              <p className="text-gray-600">
                Once a quiz or service is purchased on MSBTE Quiz Pro, no refunds will be provided.
              </p>
            </div>
            <div className="space-y-2">
              <h3 className="font-semibold text-gray-700">Processing Refunds:</h3>
              <p className="text-gray-600">
                In cases where a refund is applicable, it will be processed within 5-7 working days and credited to the customer’s bank account.
              </p>
            </div>
            <div className="space-y-2">
              <h3 className="font-semibold text-gray-700">Payment Gateway:</h3>
              <p className="text-gray-600">
                All payments on our site are processed through Razorpay payment gateway, ensuring secure and reliable transactions.
              </p>
            </div>
          </div>

          <div className="space-y-4 mt-6 mb-4">
            <h2 className="text-2xl font-semibold text-gray-800">Pricing in INR</h2>
            <div className="space-y-2">
              <h3 className="font-semibold text-gray-700">Currency:</h3>
              <p className="text-gray-600">
                All prices listed on MSBTE Quiz Pro are in Indian Rupees (INR).
              </p>
            </div>
            <div className="space-y-2">
              <h3 className="font-semibold text-gray-700">Price Changes:</h3>
              <p className="text-gray-600">
                We reserve the right to change prices at any time without prior notice.
              </p>
            </div>
          </div>

          <div className="space-y-4 mt-6 mb-4">
            <h2 className="text-2xl font-semibold text-gray-800">Shipping Policy</h2>
            <div className="space-y-2">
              <h3 className="font-semibold text-gray-700">Digital Products:</h3>
              <p className="text-gray-600">
                All quizzes and services offered on MSBTE Quiz Pro are digital and delivered online.
              </p>
            </div>
            <div className="space-y-2">
              <h3 className="font-semibold text-gray-700">Delivery Timeline:</h3>
              <p className="text-gray-600">
                Access to purchased quizzes is granted immediately upon successful payment.
              </p>
              <p className="text-gray-600">
                In case of any technical issues, access will be provided within a maximum of 24 hours.
              </p>
            </div>
          </div>



          <h2 className="text-2xl font-semibold mt-6 mb-4">
            Children's Privacy
          </h2>
          <p className="mb-6">
            Our Service does not address anyone under the age of 13. We do not
            knowingly collect personally identifiable information from anyone
            under the age of 13. If you are a parent or guardian and you are
            aware that your child has provided us with Personal Data, please
            contact us. If we become aware that we have collected Personal Data
            from anyone under the age of 13 without verification of parental
            consent, we take steps to remove that information from our servers.
          </p>
          <p className="mb-6">
            If we need to rely on consent as a legal basis for processing your
            information and your country requires consent from a parent, we may
            require your parent's consent before we collect and use that
            information.
          </p>

          <h2 className="text-2xl font-semibold mt-6 mb-4">
            Links to Other Websites
          </h2>
          <p className="mb-6">
            Our Service may contain links to other websites that are not
            operated by us. If you click on a third-party link, you will be
            directed to that third party's site. We strongly advise you to
            review the Privacy Policy of every site you visit.
          </p>
          <p className="mb-6">
            We have no control over and assume no responsibility for the
            content, privacy policies, or practices of any third-party sites or
            services.
          </p>

          <h2 className="text-2xl font-semibold mt-6 mb-4">
            Changes to This Privacy Policy
          </h2>
          <p className="mb-6">
            We may update our Privacy Policy from time to time. We will notify
            you of any changes by posting the new Privacy Policy on this page.
          </p>
          <p className="mb-6">
            We will let you know via email and/or a prominent notice on our
            Service, prior to the change becoming effective and update the "Last
            updated" date at the top of this Privacy Policy.
          </p>
          <p className="mb-6">
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.
          </p>

          <h2 className="text-2xl font-semibold mt-6 mb-4">Contact Us</h2>
          <p className="mb-6">
            If you have any questions about this Privacy Policy, you can contact
            us:
          </p>
          <ul className="list-disc pl-6 mb-6">
            <li className="mb-2">
              <strong>By email : </strong>
              <a
                href="mailtomsbtewallah@gmail.com"
                className="text-blue-500 hover:underline"
              >
                msbtewallah@gmail.com
              </a>
            </li>
            <li className="mb-2">
              <strong>By visiting this page on our website : </strong>
              <Link
                href={`${process.env.BASE_URL}/contact-us`}
                className="text-blue-500 hover:underline w-full"
              >
                Contact Us
              </Link>
            </li>
            <li className="mb-2">
              <strong>By phone number : </strong>
              <a
                href="tel:9359839551"
                className="text-blue-500 hover:underline"
              >
                9359839551
              </a>
            </li>
            <li className="mb-2">
              <strong>Operating Address : </strong>
                <p className="mt-1">
                  MSBTE Quiz pro, Village Ranzani Tal. Taloda Dist. Nandurbar, Maharashtra India - 425413
                </p>
              
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
